version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "6868:6868"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - api_nw
    depends_on:
      - company_dns

  company_dns:
    build: company_dns
    container_name: company_dns
    image: company_dns
    restart: always
    networks:
      - api_nw

networks:
  api_nw:
    driver: bridge