name: Monthly company_dns build

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            repository: 'miha42-github/company_dns'
            ref: 'main'

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
    
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}/company_dns:latest
            platforms: linux/amd64,linux/arm64
            cache-from: type=gha
            cache-to: type=gha,mode=max
            
        # Azure deployment steps
        - name: Azure Login
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - name: Deploy to Azure Container App
          uses: azure/container-apps-deploy-action@v2
          with:
            resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
            containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
            containerAppEnvironment: ${{ secrets.AZURE_CONTAINER_APP_ENV }}
            location: 'West US'
            imageToDeploy: ghcr.io/${{ github.repository }}/company_dns:latest
            yamlConfigPath: ${{ github.workspace }}/container-app-config.yaml