name: Monthly company_dns build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            repository: 'miha42-github/company_dns'
            ref: 'main'

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
    
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}/company_dns:latest